### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by gitSomS** [imsmokie/photoshop-rich-presence#1]
I am getting this message everytime i try to install, can you help me fixing it?

C:\Users\SomS\Downloads\photoshop-rich-presence>node index
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\SomS\Downloads\photoshop-rich-presence\node_modules\winprocess\build\Release\winprocess.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\SomS\Downloads\photoshop-rich-presence\node_modules\winprocess\winprocess.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

C:\Users\SomS\Downloads\photoshop-rich-presence>npm install
npm WARN discord-rpc@3.0.0 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN discord-rpc@3.0.0 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN photoshop-rich-presence@1.0.0 No repository field.

**Comment by smokes** [comment]
rewrote it in python for the sole purpose of avoiding node issues https://github.com/smokes/adobe-rpc
